# /////////////////////////////////////////////////////////////////////////////////////////////////
# docker commands:
#   docker image ls
#   docker container ls -a
#   docker rm sync-gateway
#   docker rm cb-server
#   - - or - -
#   docker container rm sync-gateway
#   docker container rm cb-server
#   docker image ls
#   docker container ls -a
#   docker-compose build
#   docker-compose build --build-arg os_platform=macos
#   DOCKER_BUILDKIT=0 docker-compose build --build-arg os_platform=macos
#   docker container inspect cb-server
#   docker container inspect sync-gateway
#   docker-compose up
#   echo "-- displaying cb-server logs ctrl-c to exit ..."
#   docker logs -f cb-server
#   echo "-- displaying sync-gateway logs ctrl-c to exit ..."
#   docker logs -f sync-gateway 
# /////////////////////////////////////////////////////////////////////////////////////////////////

version: '3.9'
services:

  couchbase:
    hostname: cb-server
    container_name: cb-server
    build:
      context: ./
      dockerfile: ./Dockerfile.cbserver
    stdin_open: true
    tty: true      
    networks:
      - workshop
    ports:
     - 8091-8096:8091-8096
     - 11210:11210
    # volumes:
    #   - ./docker/server/startup.sh:/startup.sh
    environment:  
      - CLUSTER_NAME=couchbase-demo
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=store_local
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=password
      - COUCHBASE_RBAC_NAME=admin

  sync-gateway:
    hostname: sync-gateway
    container_name: sync-gateway
    build:
      context: ./
      dockerfile: ./Dockerfile.cbsyncgateway
    # entrypoint: ["sh","/config.sh"]
    stdin_open: true
    tty: true      
    networks:
      - workshop
    ports:
      - 4984-4986:4984-4986
    depends_on:
      - couchbase
    # volumes:
    #   - ./src/sync-gateway-config.json
    environment:  
      - ADMIN_INTERFACE=:4985
      - INTERFACE=:4984
      - METRICS_INTERFACE=:4986
      - REMOTE_ADDRESS=$REMOTEIP

networks:
  workshop:
    driver: bridge

# /////////////////////////////////////////////////////////////////////////////////////////////////
